import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./layout.css"
import { NavigationResultTag } from "next/dist/client/components/segment-cache/types";
import Navigator1 from "@/components/Navigator";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body> <div className="MainPageContainer">
      <div className="TitleContainer">
        <h1>Rick & Morty</h1>
      </div>
      <Navigator1></Navigator1>
      {children}
     
    </div></body>
    </html>
  );
}
