import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./page.css";
import { PersonajeProvider } from "@/context/listaPersonaje";
import { BuscarProvider } from "@/context/searchContext";
import { Cabecera } from "@/context/cabecera";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      
      <body><PersonajeProvider><Cabecera><BuscarProvider>{children}</BuscarProvider></Cabecera></PersonajeProvider></body>
    
    </html>
  );
}