import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ListaProvider } from "@/context/ContextList";
import Buscador  from "@/components/buscador";
import { SearchProvider } from "@/context/searchContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pagina de Cocktails",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ListaProvider>
          <SearchProvider>

          
          <Buscador />
          {children}
          </SearchProvider>
        </ListaProvider>
      </body>
    </html>
  );
}
